### ISSUE TITLE
Wrong CPAN::Meta::Requirements version

### ISSUE THREAD

**Issue by aratnaweera** [dagolden/CPAN-Meta-Requirements#19]
The version of CPAN::Meta::Requirements in Check.pm is not consistant with what is mentioend elsewhere, and this breaks creating RPMs of this package.  The following patch fixes it, please apply.  Thanks!

--- CPAN-Meta-Check-0.009.orig/lib/CPAN/Meta/Check.pm   2014-06-20 19:37:50.000000000 +0200
+++ CPAN-Meta-Check-0.009/lib/CPAN/Meta/Check.pm        2015-01-25 09:58:07.366002061 +0100
@@ -8,7 +8,7 @@
 our @EXPORT_OK = qw/check_requirements requirements_for verify_dependencies/;
 our %EXPORT_TAGS = (all => [ @EXPORT, @EXPORT_OK ] );
 
-use CPAN::Meta::Requirements 2.120920;
+use CPAN::Meta::Requirements 2.121;
 use Module::Metadata;
 
 sub _check_dep {

**Comment by dagolden** [comment]
This isn't a bug in CPAN::Meta::Requirements.  You need to report this against CPAN::Meta::Check.

That said, I don't see anything wrong with the line you changed.  You might want to ask on the `#toolchain` channel on irc.perl.org about how to normalize package version numbers for use in packaging.

**Comment by karenetheridge** [comment]
yes, I don't understand what is broken with the original code?  Can you
show what packaging error you are getting?

**Comment by aratnaweera** [comment]
Oops...

Sorry about reporting to the wrong place.  The patch itself is against CPAN::Meta::Check!!!

CPAN::Meta::Check depends on CPAN::Meta::Requirements 2.121 or above, and it is mentioned everywhere in the source tarball, except in Check.pm file itself, where it [incorrectly] mentions the CPAN::Meta version it requires, hence the error.

Again, apologies for posting in the wrong place, will post against CPAN::Meta::Check.

**Comment by karenetheridge** [comment]
looks like it is already here -- https://github.com/Leont/cpan-meta-check/pull/7
